name = "Ares Mod - Achilles Expansion (0.0.6d)";
picture = "\achilles\data_f_achilles\pictures\Achilles_Icon_005.paa";
author = "Ares by Anton Struyk, AE by Kex";
description = "Ares Mod - Achilles Expansion (0.0.6d)";
logo = "\achilles\data_f_achilles\pictures\Achilles_Icon_005.paa";
logoSmall = "\achilles\data_f_achilles\icons\icon_achilles_small.paa";
logoOver = "\achilles\data_f_achilles\pictures\Achilles_Icon_005.paa";
tooltip = "Ares Mod - Achilles Expansion (0.0.6d)";
tooltipOwned = "Ares Mod - Achilles Expansion Owned";
actionName = "Website";
action = "https://forums.bistudio.com/topic/191113-ares-mod-achilles-expansion/?p=3031548";
overview = "Ares augments the existing Zeus functionality, expanding the toolset and making it easy to create more compelling missions on the fly.<br />The Achilles Expansion (AE) includes Ares Mod with even more functionalites. Some functionalities only work with ACE mod, but those mods are not mandatory in order to run Ares (AE) properly.";
overviewPicture = "\achilles\data_f_achilles\pictures\Achilles_Icon_005.paa";
overviewText = "Ares Mod - Achilles Expansion (0.0.6d)";