jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip setuptools wheel
        displayName: 'Install pip'

      - script: pip install sphinx
        displayName: 'Install Sphinx'

      - script: sphinx-build -nWT -b dummy docs/source/ docs/build/html
        displayName: 'Build documentation'

  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          ./tools/make.ps1
        displayName: 'Install armake'

      - bash: |
          make releaseCI
        displayName: 'Build with armake'

      - powershell: |
          ls *.tar.gz
          mv (ls *.tar.gz).Name $(Build.ArtifactStagingDirectory)
          ls $(Build.ArtifactStagingDirectory)
        displayName: 'Move tar to Artifact Directory'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: releaseZip

  - job: Release

    dependsOn:
      - Test
      - Build

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: single
          artifactName: releaseZip
          pathtoPublish: $(Build.ArtifactStagingDirectory)

      - script: |
          cd $(Build.ArtifactStagingDirectory)/releaseZip
          export ZIP=$(ls *.tar.gz | head -n1)
          export ZIP_NAME=$(echo $ZIP | sed 's/.......$//')
          echo $ZIP
          echo $ZIP_NAME
          ls
          tar xzf $ZIP
          ls
          zip -qr $ZIP_NAME.zip \@achilles
          ls
          curl -F 'zip=@'"$ZIP_NAME.zip"'' -F 'accessToken=$(access.token)' $(access.url)
        displayName: 'Upload files'
