jobs:
  - job: Test
    pool:
      vmImage: 'ubuntu-16.04'

    steps:
      - task: UsePythonVersion@0
        inputs:
          versionSpec: '3.7'
          architecture: 'x64'

      - script: python -m pip install --upgrade pip setuptools wheel
        displayName: 'Install pip'

      - script: pip install sphinx
        displayName: 'Install Sphinx'

      - script: sphinx-build -nWT -b dummy docs/source/ docs/build/html
        displayName: 'Build documentation'

  - job: Build
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - powershell: |
          ./tools/make.ps1
        displayName: 'Install armake'

      - bash: |
          make releaseCI
          mv $(ls *.tar.gz | head -n1) $(Build.ArtifactStagingDirectory)/$(ls *.tar.gz | head -n1)
        displayName: 'Build with armake'

      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: $(Build.ArtifactStagingDirectory)
          artifactName: releaseZip

  - job: Release

    dependsOn:
      - Test
      - Build

    steps:
      - task: DownloadBuildArtifacts@0
        inputs:
          buildType: current
          downloadType: single
          artifactName: releaseZip
          pathtoPublish: $(Build.ArtifactStagingDirectory)

      - script: |
          cd $(Build.ArtifactStagingDirectory)/releaseZip
          export ZIP=$(ls *.tar.gz | head -n1)
          export ZIP_NAME=$(echo $ZIP | sed 's/....$//')
          tar xzf $ZIP && zip $ZIP_NAME.zip $(tar tf $ZIP)
          curl -F 'zip=@'"$ZIP"'' -F 'accessToken=$(access.token)' $(access.url)
        displayName: 'Upload files'
