jobs:
- job: Test
  pool:
    vmImage: 'ubuntu-16.04'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.7'
      architecture: 'x64'

  - script: python -m pip install --upgrade pip setuptools wheel
    displayName: 'Install pip'

  - script: pip install sphinx
    displayName: 'Install Sphinx'

  - script: sphinx-build -nWT -b dummy docs/source/ docs/build/html
    displayName: 'Build documentation'
  
- job: Build
  steps:
  - script: |
      sudo add-apt-repository ppa:koffeinflummi/armake
      sudo apt-get update
      sudo apt-get install armake
    displayName: 'Install armake'

  - script: |
      sed --version
      armake -v
      zip -v
    displayName: 'Dependency versions'

  - script: |
      make releaseCI
    displayName: 'Build with armake'

  - task: PublishPipelineArtifact@0
    inputs:
      artifactName: 'releaseZip'
      targetPath: $(System.DefaultWorkingDirectory)/release

- job: Release
  dependsOn:
    - Test
    - Build
  steps:
    - task: DownloadPipelineArtifact@0
      inputs:
        artifactName: 'releaseZip'
        targetPath: $(System.DefaultWorkingDirectory)/release

    - script: "cd release && curl -F 'zip=@$(ls *.zip | head -n1)' -F 'accessToken=$(access.token)' $(access.url)"
      displayName: 'Upload files'
