// Modules to include in the tree.

units[] =
{
	"Ares_Module_Add_All_Objects_To_Curator",
	"Ares_Module_Behaviour_Create_Artillery_Target",
	"Ares_Module_Behaviour_Patrol",
	"Ares_Module_Behaviour_Search_Nearby_And_Garrison",
	"Ares_Module_Behaviour_Search_Nearby_Building",
	"Ares_Module_Equipment_Lights",
	"Ares_Module_Equipment_Nvgs",
	"Ares_Module_Equipment_Thermals",
	"Ares_Module_Execute_Code",
	"Ares_Module_Garrison_Nearest",
	"Ares_Module_Reinforcements_Create_Lz",
	"Ares_Module_Reinforcements_Create_Rp",
	"Ares_Module_Reinforcements_Spawn_Units",
	"Ares_Module_Remove_Objects_From_Curator",
	"Ares_Module_Spawn_Custom_Mission_Objects",
	"Ares_Module_Spawn_Smoke",
	"Ares_Module_Spawn_Submarine",
	"Ares_Module_Spawn_Trawler",
	"Ares_Module_SurrenderSingleUnit",
	"Ares_Module_Teleport_All",
	"Ares_Module_Teleport_CreateTeleporter",
	"Ares_Module_Teleport_Group",
	"Ares_Module_Teleport_Side_Civilian",
	"Ares_Module_Teleport_Side_Csat",
	"Ares_Module_Teleport_Side_Independent",
	"Ares_Module_Teleport_Side_Nato",
	"Ares_Module_Teleport_Single",
	"Ares_Module_Teleport_Zeus",
	"Ares_Module_UnGarrison",
	"Ares_Module_Util_Create_Composition",
	"Ares_Module_Util_Remove_Nearest_Persistent",
	"Ares_Module_Teleport",
	// "Ares_Module_Behaviour_Land_Helicopter",
	//#include "units_customModules.hpp"
};
