// Modules to include in the tree.

units[] =
{
	"Ares_Module_Arsenal_AddCustom",
	"Ares_Module_Arsenal_Copy_To_Clipboard",
	"Ares_Module_Arsenal_Paste_Replace",
	"Ares_Module_Arsenal_Paste_Combine",
	"Ares_Module_Arsenal_Create_Nato",
	"Ares_Module_Arsenal_Create_Csat",
	"Ares_Module_Arsenal_Create_Aaf",
	"Ares_Module_Arsenal_Create_Guerilla",
	"Ares_Module_Behaviour_Patrol",
	"Ares_Module_Behaviour_Search_Nearby_And_Garrison",
	"Ares_Module_Behaviour_Search_Nearby_Building",
	"Ares_Module_Equipment_Lights",
	"Ares_Module_Equipment_Nvgs",
	"Ares_Module_Equipment_Thermals",
	"Ares_Module_Execute_Code",
	"Ares_Module_Garrison_Nearest",
	"Ares_Module_Reinforcements_Create_Lz",
	"Ares_Module_Reinforcements_Create_Rp",
	"Ares_Module_Reinforcements_Spawn_Units",
	"Ares_Module_Spawn_Submarine",
	"Ares_Module_Spawn_Trawler",
	"Ares_Module_SurrenderSingleUnit",
	"Ares_Module_UnGarrison",
	"Ares_Module_Teleport",
	"Ares_Module_Add_Remove_Editable_Objects",
	"Ares_Module_Zeus_Visibility",
	"Ares_Module_Hint",
	"Ares_Module_Switch_Side",
	"Ares_Module_Change_Player_Side",
	"Ares_Module_Create_Teleporter",
	"Ares_Module_Spawn_Effects",
	"Ares_Module_Spawn_Intel",
	"Ares_Module_Arsenal_AddFull",
	"Ares_Module_Create_Mission_SQF",
	"Ares_Module_Spawn_Advanced_Composition",
	"Ares_Module_Spawn_Explosives",
	"ModulePunishment_F",
	"Ares_Module_Manage_Advanced_Compositions"
	// "Ares_Module_Behaviour_Land_Helicopter",
	//#include "units_customModules.hpp"
};
